sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  # 是否屏蔽jwt令牌
  jwt:
    isHidden: true
  thread:
    corePoolSize: 4
    maxPoolSize: 8
    queueCapacity: 10
    keepAliveSeconds: 5