sky:
   server:
          port: 8082
   datasource:
          driver-class-name: com.mysql.cj.jdbc.Driver
          host: 123.56.162.2
          port: 3306
          database: sky_take_out
          username: root
          password: 20001126X.