sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 123.56.162.2
    port: 3399
    url: jdbc:mysql://123.56.162.2:3399/sky_take_out
    database: sky_take_out
    username: gali
    password: 20001126X
  wechat:
    appid: xxx
    secert: xxx
  # 是否屏蔽jwt令牌
  jwt:
    isHidden: true
  # 线程池配置
  thread:
    corePoolSize: 2
    maxPoolSize: 4
    queueCapacity: 6
    keepAliveSeconds: 5
spring:
  devtools:
    restart:
      enabled: false
